version: '3'

services:
    telegram-bot:
        build: telegram-bot
    consumer-proxy:
        build: consumer-proxy
    mosquitto:
        image: eclipse-mosquitto
        ports:
        - 1883:1883
        volumes:
        - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
        - ./mosquitto/data:/mosquitto/data
        - ./mosquitto/log:/mosquitto/log
